# $schema: https://raw.githubusercontent.com/robo9k/http-base-uri-rs/refs/heads/main/config.schema.json
"$schema" = 'https://raw.githubusercontent.com/robo9k/http-base-uri-rs/refs/heads/main/config.schema.json'
